name: powerstack
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - geopandas
  - shapely
  - pyproj
  - pyarrow
  - scikit-learn
  - matplotlib
  - folium
  - truststore
  - osmnx=2.1.1
  - osmium-tool
  - requests
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - duckdb==1.5.5
      - streamlit
      - streamlit-folium
